codecov:
  require_ci_to_pass: true
comment:
  behavior: default
  layout: reach,diff,flags,files,footer
  require_changes: false
coverage:
  precision: 2
  range:
  - 90.0
  - 100.0
  round: down
  status:
    patch:
      default:
        target: auto
        threshold: 0.0
    project:
      default:
        if_ci_failed: error
        only_pulls: false
        target: 80.0
        threshold: 0.0
ignore:
- (?s:.*/[^\/]+Test\.cs.*)\Z
- "Utilities"
- (?s:.*/PlayerActions.*)\Z
parsers:
  gcov:
    branch_detection:
      conditional: true
      loop: true
      macro: false
      method: false
