- name: Project builder
- uses: game-ci/unity-builder@v2
  env:
    UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
    UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
    UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
  with:
    targetPlatform: iOS
    name: Build
    path: build


- name: Push directory to another repository
  uses: cpina/github-action-push-to-another-repository@v1.5
  with:
    source-directory: 'build'
    destination-github-username: ' rcq-arcade-esiee-it'
    destination-repository-name: 'RCQ-ARCADE-PROD'
    user-email: sajous.davenese@gmail.com
    target-branch: test
